// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4sC0LnqYiJKl6OWfg7G96P1wGpYRUn8A',
    appId: '1:893387432004:web:7aa7220369c593b1f7dc11',
    messagingSenderId: '893387432004',
    projectId: 'reciprocal-cd0dc',
    authDomain: 'reciprocal-cd0dc.firebaseapp.com',
    storageBucket: 'reciprocal-cd0dc.firebasestorage.app',
    measurementId: 'G-GV21PGG2DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcQTMS7QTwMxGP-Age0paymolqk6q6A9Y',
    appId: '1:893387432004:android:7fc9c5748ffca655f7dc11',
    messagingSenderId: '893387432004',
    projectId: 'reciprocal-cd0dc',
    storageBucket: 'reciprocal-cd0dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIxxNrTtz-eTZ3tN-u88n4ybr0GMx5apk',
    appId: '1:893387432004:ios:8029ed7d0b04eb18f7dc11',
    messagingSenderId: '893387432004',
    projectId: 'reciprocal-cd0dc',
    storageBucket: 'reciprocal-cd0dc.firebasestorage.app',
    iosBundleId: 'com.example.reciprocalTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIxxNrTtz-eTZ3tN-u88n4ybr0GMx5apk',
    appId: '1:893387432004:ios:8029ed7d0b04eb18f7dc11',
    messagingSenderId: '893387432004',
    projectId: 'reciprocal-cd0dc',
    storageBucket: 'reciprocal-cd0dc.firebasestorage.app',
    iosBundleId: 'com.example.reciprocalTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4sC0LnqYiJKl6OWfg7G96P1wGpYRUn8A',
    appId: '1:893387432004:web:dcf7bdc043df09b2f7dc11',
    messagingSenderId: '893387432004',
    projectId: 'reciprocal-cd0dc',
    authDomain: 'reciprocal-cd0dc.firebaseapp.com',
    storageBucket: 'reciprocal-cd0dc.firebasestorage.app',
    measurementId: 'G-XB85YCJZ8Q',
  );
}
